[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"

[lib]
name = "todo"
path = "src/todo/lib.rs"

[[bin]]
path = "src/main.rs"
name = "todo"
doc = false
